const FAIL_GET_MIND_MAPS = 'Failed to get mind-maps';
const FAIL_DELETE_MIND_MAP = '삭제권한이 없습니다.';
const FAIL_DELETE_MIND_MAP_BY_SERVER_PROBLEM = '삭제권한이 없습니다.';

const FAIL_CHANGE_MIND_MAP_PUBLIC_OPTION = '변경권한이 없습디다.';

module.exports = {
  FAIL_GET_MIND_MAPS,
  FAIL_DELETE_MIND_MAP,
  FAIL_DELETE_MIND_MAP_BY_SERVER_PROBLEM,
  FAIL_CHANGE_MIND_MAP_PUBLIC_OPTION,
};
